### ISSUE TITLE
failed running Openpiv_Python_Tutorial_Basic.ipynb 

### ISSUE THREAD

**Issue by ruinianxu** [OpenPIV/openpiv-python-gpu#21]
**Describe the bug**
Run ```Openpiv_Python_Tutorial_Basic.ipynb``` will give us the following error. I've made sure that pycuda has the same version which is 2021.1. The only difference might be CUDA. Mine is 11.6 while the one in notebook is 11.2. Could you give me some hints about how to address this issue?

```
/home/ruinian/Software/anaconda3/envs/openpiv-gpu/lib/python3.7/site-packages/skcuda/cublas.py:284: UserWarning: creating CUBLAS context to get version number
  warnings.warn('creating CUBLAS context to get version number')
examples/Openpiv_Python_Tutorial_Basic.py:29: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  frame_a = io.imread('openpiv/examples/test1/exp1_001_a.bmp')
examples/Openpiv_Python_Tutorial_Basic.py:30: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  frame_b = io.imread('openpiv/examples/test1/exp1_001_b.bmp')
//////////////////////////////////////////////////////////////////
ITERATION 0
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: context is destroyed
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: context is destroyed
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: context is destroyed
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: context is destroyed
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: context is destroyed
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: context is destroyed
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: context is destroyed
Traceback (most recent call last):
  File "examples/Openpiv_Python_Tutorial_Basic.py", line 33, in <module>
    x, y, u, v, mask, s2n = gpu_process.gpu_piv(frame_a, frame_b, **pars)
  File "openpiv/gpu_process.pyx", line 923, in openpiv.gpu_process.gpu_piv
    u, v = piv_gpu(frame_a, frame_b)
  File "openpiv/gpu_process.pyx", line 1248, in openpiv.gpu_process.PIVGPU.__call__
    gpu_update(d_f, self.i_peak[:n_row[K], :n_col[K]], self.j_peak[:n_row[K], :n_col[K]], n_row[K], n_col[K], K)
  File "openpiv/gpu_process.pyx", line 1651, in openpiv.gpu_process.gpu_update
    mod_update = SourceModule("""
  File "/home/ruinian/Software/anaconda3/envs/openpiv-gpu/lib/python3.7/site-packages/pycuda/compiler.py", line 363, in __init__
    self.module = module_from_buffer(cubin)
pycuda._driver.LogicError: cuModuleLoadDataEx failed: context is destroyed -
```

**Comment by alexlib** [comment]
Not sure I know how to fix it. I see this is usually a threading issue 

https://stackoverflow.com/questions/64994346/pycuda-logicerror-cumoduleloaddataex-failed-an-illegal-memory-access-was-encou

**Comment by alexlib** [comment]
https://colab.research.google.com/github/ericyang125/openpiv-python-gpu/blob/master/Openpiv_Python_Tutorial_Basic.ipynb

is running, update your branch from this fork

**Comment by ruinianxu** [comment]
cuda 10.1 will resolve the issue.
